from enum import Enum


class _ValueEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class Arm(_ValueEnum):
    DIRECT = "C1"
    STRICT_PLANNER = "C2"
    BUDGET_MATCHED_DIRECT = "C1_BUDGETED"


class Stage(_ValueEnum):
    LOAD_CONFIG = "LOAD_CONFIG"
    PREPARE_TARGET = "PREPARE_TARGET"
    LOAD_HISTORY = "LOAD_HISTORY"
    LOAD_OR_GENERATE_HYPOTHESIS = "LOAD_OR_GENERATE_HYPOTHESIS"
    FREEZE_HYPOTHESIS = "FREEZE_HYPOTHESIS"
    GENERATE_TRIGGER_PLAN = "GENERATE_TRIGGER_PLAN"
    VALIDATE_TRIGGER_PLAN = "VALIDATE_TRIGGER_PLAN"
    GENERATE_TEST = "GENERATE_TEST"
    PREFLIGHT_TEST = "PREFLIGHT_TEST"
    EXECUTE_BUGGY = "EXECUTE_BUGGY"
    EXECUTE_FIXED = "EXECUTE_FIXED"
    EVALUATE = "EVALUATE"
    PERSIST = "PERSIST"
    REPORT = "REPORT"


class ArtifactStatus(_ValueEnum):
    FROZEN = "FROZEN"
    VALID = "VALID"
    GENERATED = "GENERATED"
    EXECUTABLE = "EXECUTABLE"
    PREFLIGHT_FAILURE = "PREFLIGHT_FAILURE"
    MODEL_OUTPUT_FAILURE = "MODEL_OUTPUT_FAILURE"
    COMPLETE = "COMPLETE"


class ExecutionState(_ValueEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    MECHANICAL_FAILURE = "MECHANICAL_FAILURE"
    TIMEOUT = "TIMEOUT"


class FailureType(_ValueEnum):
    NONE = ""
    ASSERTION_FAILURE = "ASSERTION_FAILURE"
    TARGET_EXCEPTION = "TARGET_EXCEPTION"
    MECHANICAL_FAILURE = "MECHANICAL_FAILURE"
    MODEL_OUTPUT_FAILURE = "MODEL_OUTPUT_FAILURE"


class PairClassification(_ValueEnum):
    PASS = "PASS"
    ASSERTION_FAILURE = "ASSERTION_FAILURE"
    TARGET_EXCEPTION = "TARGET_EXCEPTION"
    MECHANICAL_FAILURE_STATE = "MECHANICAL_FAILURE"
    MODEL_OUTPUT_FAILURE_STATE = "MODEL_OUTPUT_FAILURE"
    F2P = "F2P"
    F2F = "F2F"
    P2P = "P2P"
    P2F = "P2F"
    NO_SUPPORTED_HYPOTHESIS = "NO_SUPPORTED_HYPOTHESIS"
    UNSUPPORTED_ORACLE = "UNSUPPORTED_ORACLE"
    MECHANICAL_FAILURE = "MECHANICAL_FAILURE"
    MODEL_OUTPUT_FAILURE = "MODEL_OUTPUT_FAILURE"


class FailureCategory(_ValueEnum):
    PASS = "PASS"
    ASSERTION_FAILURE = "ASSERTION_FAILURE"
    TARGET_EXCEPTION = "TARGET_EXCEPTION"
    F2P = "F2P"
    F2F = "F2F"
    P2P = "P2P"
    P2F = "P2F"
    NO_SUPPORTED_HYPOTHESIS = "NO_SUPPORTED_HYPOTHESIS"
    VALID_ASSERTION_F2P = "VALID_ASSERTION_F2P"
    VALID_EXCEPTION_F2P = "VALID_EXCEPTION_F2P"
    TRIGGER_TOO_WEAK = "TRIGGER_TOO_WEAK"
    SEMANTIC_NON_TRIGGER = "SEMANTIC_NON_TRIGGER"
    TRIGGER_WRONG_SHAPE = "TRIGGER_WRONG_SHAPE"
    WRONG_MECHANISM = "WRONG_MECHANISM"
    MECHANICAL_FAILURE = "MECHANICAL_FAILURE"
    MODEL_OUTPUT_FAILURE = "MODEL_OUTPUT_FAILURE"
    UNSUPPORTED_ORACLE = "UNSUPPORTED_ORACLE"
    VALID_PLAN = "VALID_PLAN"
    MALFORMED_SCHEMA = "MALFORMED_SCHEMA"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    UNSUPPORTED_ACTION = "UNSUPPORTED_ACTION"
    INCOMPLETE_STATE_TRANSITION = "INCOMPLETE_STATE_TRANSITION"
    OBSERVABLE_UNAVAILABLE = "OBSERVABLE_UNAVAILABLE"
    ASSERTION_MISALIGNED = "ASSERTION_MISALIGNED"
    LEAKAGE_CONTROL = "LEAKAGE_CONTROL"
    DUPLICATE_PLAN = "DUPLICATE_PLAN"
